ALTER TABLE RejectedCredit
ALTER COLUMN AmountRequested FLOAT;

ALTER TABLE RejectedCredit
ALTER COLUMN ApplicationDate DATE;

ALTER TABLE RejectedCredit
ALTER COLUMN LoanTitle NVARCHAR(500);

ALTER TABLE RejectedCredit
ALTER COLUMN Risk_Score FLOAT;

ALTER TABLE CreditScoreDATA.dbo.RejectedCredit
ALTER COLUMN DebtToIncomeRatio VARCHAR(20);

ALTER TABLE RejectedCredit
ALTER COLUMN ZipCode NVARCHAR(10);

ALTER TABLE RejectedCredit
ALTER COLUMN State NVARCHAR(10);

ALTER TABLE RejectedCredit
ALTER COLUMN EmploymentLength NVARCHAR(20);

ALTER TABLE RejectedCredit
ALTER COLUMN PolicyCode FLOAT;